### ISSUE TITLE
Convert Resume Upload to Two Block Text Inputs (Resume & Job Description)

### ISSUE THREAD

**Issue by mSaadSalman** [DSC-McMaster-U/InterviewGeniusAI#16]
Description: We need to modify the existing resume upload feature by replacing it with two block text inputs. Users will now manually input text into one block for their resume and another block for the job description. This will streamline the process and allow users to paste relevant content directly into the fields.

Requirements:

Block Text Input Fields:
Replace the resume file upload with two large block text input fields:
Block 1: Resume – Users will input their entire resume here, including personal information, education, experience, skills, etc.
Block 2: Job Description – Users will input the job description of the role they are applying for.

**Comment by shadielfares** [comment]
Completed, please check work.

**Comment by shadielfares** [comment]
My branch was merged with the above functionalities, closing issue
